name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install pytest

      - name: Rodar testes
        run: pytest
